version: '3'

services:
  app1:
    build: ./app1
    ports:
      - "3000:3000"
  app2:
    build: ./app2
    ports:
      - "3001:3001"
    environment:
      APP_URL: http://app1:3000
    depends_on:
      - app1
